In [2]:
import collections
import numpy as np
import tensorflow as tf
import tensorflow_federated as tff
from scipy.stats import ks_2samp, chi2_contingency
import concurrent.futures


In [3]:
# Load the MNIST dataset
mnist = tf.keras.datasets.mnist
(X_train, Y_train), (X_test, Y_test) = mnist.load_data()

In [4]:
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(60000, 28, 28)
(10000, 28, 28)
(60000,)
(10000,)


In [5]:
X_train[0][6]

array([  0,   0,   0,   0,   0,   0,   0,   0,  30,  36,  94, 154, 170,
       253, 253, 253, 253, 253, 225, 172, 253, 242, 195,  64,   0,   0,
         0,   0], dtype=uint8)

In [6]:
# Normalize the data
X_train, X_test = X_train / 255.0, X_test / 255.0

In [7]:
X_train[0][6]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.11764706, 0.14117647,
       0.36862745, 0.60392157, 0.66666667, 0.99215686, 0.99215686,
       0.99215686, 0.99215686, 0.99215686, 0.88235294, 0.6745098 ,
       0.99215686, 0.94901961, 0.76470588, 0.25098039, 0.        ,
       0.        , 0.        , 0.        ])

In [8]:
# Define a model creation function
def create_model():
    model = tf.keras.Sequential([
        tf.keras.layers.Flatten(input_shape=(28, 28)),
        tf.keras.layers.Dense(128, activation='relu'),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(10, activation='softmax')
    ])
    return model

####  We have to convert our keras model to tff model
  This is necessary because TFF operates on its own set of model interfaces that are designed to be compatible with federated computations

In a federated learning setting, the model needs to be serialized and sent to multiple clients, where it will be used to compute updates locally.
These updates are then sent back to the server where they are aggregated. 
This process requires the model to have certain properties and methods that are not present in a standard Keras model.

In [9]:
# Convert Keras model to TFF model
def model_fn():
    keras_model = create_model()
    return tff.learning.from_keras_model(
        keras_model,
        input_spec=client_datasets[0].element_spec,
        
        #means that the input specification is based on the first client dataset. This assumes that all client datasets have the same format
        #used to specify the type and shape of the data that the model expects for its inputs
        #The element_spec property of a tf.data.Dataset object gives the shape and type information of the dataset elements
        
        loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
        metrics=[tf.keras.metrics.SparseCategoricalAccuracy()]
    )
    
# The tff.learning.from_keras_model function takes a Keras model and wraps it in a TFF model interface,
# which includes methods for sending the model to clients,
# computing updates, and aggregating updates on the server.
# It also includes methods for training, evaluation, and prediction that can be used in a federated setting.    

In [10]:
# Set the number of clients in the federated learning system
num_clients = 2

# Initialize an empty list to hold the datasets for each client
client_datasets = []

# Create a dataset for each client
for _ in range(num_clients):
    # Generate 50 random 28x28 images (values between 0 and 1)
    images = np.random.rand(50, 28, 28)
    
    # Generate 50 random labels (integers between 0 and 9)
    labels = np.random.randint(0, 10, 50)
    
    # Create a dataset from the images and labels
    dataset = tf.data.Dataset.from_tensor_slices((images, labels))
    
    # Batch the dataset into groups of 10
    batched_dataset = dataset.batch(10)
    #.batch(10): This batches the dataset into batches of 10 elements each.
    # This means that during training, the model will be updated based on 10 examples at a time.
    
    # Add the batched dataset to the list of client datasets
    client_datasets.append(batched_dataset)


In [11]:
# Create dummy client datasets (reduced size)
# num_clients = 10
# client_datasets = [tf.data.Dataset.from_tensor_slices((np.random.rand(50, 28, 28), np.random.randint(0, 10, 50))).batch(10) for _ in range(num_clients)]

this part of the code is creating a list of federated learning algorithms, one for each client in the system

In [12]:
# Create federated learning algorithms for each client
federated_algorithms = [tff.learning.build_federated_averaging_process(
    # This function is used to build a Federated Averaging process in TensorFlow Federated
    
    model_fn,
    # means that this model will be used for the federated learning process
    
    client_optimizer_fn=lambda: tf.keras.optimizers.SGD(learning_rate=0.02),
    # This is a function that returns an optimizer for updating the model parameters on the clients
    
    
    server_optimizer_fn=lambda: tf.keras.optimizers.SGD(learning_rate=1.0)
    # This is a function that returns an optimizer for updating the global model parameters on the server
    
) for _ in range(num_clients)]


len(federated_algorithms)

2

## A Way to Initialize the federated algorithm asynchronously

this part of the code is a way to initialize a federated learning algorithm asynchronously, i.e., without blocking the rest of your program. This can be useful if the initialization process is time-consuming and you want to do other things while it’s happening. However, in this specific case, the code immediately waits for the result after submitting the function, so it doesn’t actually take advantage of the asynchronous execution.

In [13]:
def initialize_algorithm(algorithm):
    tff.backends.native.set_local_execution_context()
    return algorithm.initialize()



with concurrent.futures.ThreadPoolExecutor() as executor:
    future = executor.submit(initialize_algorithm, federated_algorithms[0])
    state = future.result()

print('Initial state:', state)


Initial state: ServerState(model=ModelWeights(trainable=[array([[ 0.05836407,  0.05039725, -0.04177264, ..., -0.04224399,
         0.0736633 ,  0.06586737],
       [ 0.05985995, -0.06860409,  0.074465  , ..., -0.0594831 ,
        -0.03691043, -0.04610123],
       [-0.0575145 , -0.0635508 , -0.00300542, ...,  0.03533187,
         0.00281896, -0.01152197],
       ...,
       [ 0.05009299, -0.07541757, -0.02664017, ...,  0.02485169,
         0.02423824, -0.01720573],
       [-0.06613451, -0.0512032 , -0.0610115 , ...,  0.06814782,
        -0.0532575 , -0.07847326],
       [-0.04616087,  0.01027688, -0.03871288, ...,  0.06158916,
        -0.03632533, -0.02753006]], dtype=float32), array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.,

model: This is the initial model weights. It’s divided into trainable and non_trainable weights. The trainable weights are the ones that the algorithm will update during training. In this case, they are initialized with random values.

optimizer_state: This is the state of the optimizer. It can include things like the current step number, momentum variables for optimizers like Adam or RMSProp, etc. In this case, it’s just the current step number, initialized to 0.

delta_aggregate_state and model_broadcast_state: These are used by the server to aggregate the model updates from the clients (delta_aggregate_state) and broadcast the updated model back to the clients (model_broadcast_state). In this case, they are both empty because no updates have been performed yet.

In [14]:
# Function to run the training in a separate event loop
def run_training():
    
    tff.backends.native.set_local_execution_context()
    # This sets up the execution context for TensorFlow Federated (TFF) in the local machine

    states = [algorithm.initialize() for algorithm in federated_algorithms]
    # This initializes the state of each federated learning algorithm
    # The state includes the model parameters and any other variables that the algorithm needs to keep track of

    # Train the models on the clients' data (reduced to 2 rounds)
    for round_num in range(1, 3):
        print(f"Round {round_num}")
        for client_id in range(num_clients):
            states[client_id], _ = federated_algorithms[client_id].next(states[client_id], [client_datasets[client_id]])

        # Perform differential testing for each pair of clients
        for i in range(num_clients):
            for j in range(i+1, num_clients):
                # Get the model weights after training
                weights_i = states[i].model.trainable
                weights_j = states[j].model.trainable

                # Evaluate both models on train and test data
                train_predictions_i, train_labels = evaluate_model_on_data(weights_i, create_model, X_train[:1000], Y_train[:1000])
                test_predictions_i, test_labels = evaluate_model_on_data(weights_i, create_model, X_test[:1000], Y_test[:1000])
                train_predictions_j, _ = evaluate_model_on_data(weights_j, create_model, X_train[:1000], Y_train[:1000])
                test_predictions_j, _ = evaluate_model_on_data(weights_j, create_model, X_test[:1000], Y_test[:1000])

                # Perform differential testing
                print(f"Comparison between Client {i} and Client {j}:")
                perform_differential_testing(train_predictions_i, train_predictions_j, train_labels, "Train")
                perform_differential_testing(test_predictions_i, test_predictions_j, test_labels, "Test")
                print()

        # Average the predictions after differential testing
        average_predictions_train = np.mean([evaluate_model_on_data(state.model.trainable, create_model, X_train[:1000], Y_train[:1000])[0] for state in states], axis=0)
        average_predictions_test = np.mean([evaluate_model_on_data(state.model.trainable, create_model, X_test[:1000], Y_test[:1000])[0] for state in states], axis=0)

        print("Average predictions on Train Data:")
        print(average_predictions_train)
        print("Average predictions on Test Data:")
        print(average_predictions_test)

In [15]:
# Function to evaluate the model on data
def evaluate_model_on_data(weights, create_model_fn, X, Y):
    model = create_model_fn()
    model.set_weights(weights)
    predictions = model.predict(X)
    return predictions, Y

In [16]:
# Function to perform differential testing
def perform_differential_testing(predictions_i, predictions_j, labels, data_type):
    # Criterion 1: Absolute differences between classes
    pred_class_i = np.argmax(predictions_i, axis=1)
    pred_class_j = np.argmax(predictions_j, axis=1)
    Δ_class = np.sum(pred_class_i != pred_class_j)

    # Criterion 2: Absolute differences between scores
    Δ_score = np.sum(predictions_i != predictions_j)

    # Criterion 3: Significance of difference between scores
    P_KS = ks_2samp(predictions_i.flatten(), predictions_j.flatten()).pvalue

    # Criterion 4: Significance of difference between classifications
    contingency = np.array([[np.sum((pred_class_i == k) & (pred_class_j == l)) for l in range(10)] for k in range(10)])
    contingency += 1  # Add-one smoothing
    P_X2 = chi2_contingency(contingency)[1]

    print(f"{data_type} Data:")
    print(f"Δ_class: {Δ_class}")
    print(f"Δ_score: {Δ_score:.2f}")
    print(f"P_KS: {P_KS:.4f}")
    print(f"P_X2: {P_X2:.4f}")
    
    if P_KS < 0.05 or P_X2 < 0.05:
        print("Warning: Significant difference detected (p-value < 0.05)")

In [17]:
# Run the training
with concurrent.futures.ThreadPoolExecutor() as executor:
    future = executor.submit(run_training)
    future.result()


Round 1
Comparison between Client 0 and Client 1:
Train Data:
Δ_class: 980
Δ_score: 10000.00
P_KS: 0.0000
P_X2: 0.0000
Test Data:
Δ_class: 975
Δ_score: 10000.00
P_KS: 0.0000
P_X2: 0.0000

Average predictions on Train Data:
[[0.05633319 0.14268357 0.09179597 ... 0.1419983  0.07862744 0.08928493]
 [0.07029216 0.11421728 0.12545967 ... 0.11117096 0.05623373 0.08167334]
 [0.09671271 0.1045723  0.13536033 ... 0.08277664 0.09316494 0.10946634]
 ...
 [0.05059628 0.16004598 0.11543691 ... 0.08459924 0.06276383 0.07659651]
 [0.0657655  0.14488554 0.10034356 ... 0.08232808 0.04641693 0.07233499]
 [0.06407616 0.16336723 0.08270907 ... 0.08378872 0.083827   0.07262444]]
Average predictions on Test Data:
[[0.06192347 0.12433006 0.13117662 ... 0.12946817 0.09776523 0.0848494 ]
 [0.07834484 0.11880942 0.10034712 ... 0.16962367 0.05097678 0.08333739]
 [0.08361384 0.09398962 0.12373546 ... 0.08991857 0.10353357 0.10349587]
 ...
 [0.063291   0.19096759 0.1065729  ... 0.09190824 0.04512028 0.11240079]
 [